
import pytest

from app.ai.utils.json_parser import extract_json_from_text


def test_extract_direct_json():
    raw = '{"name": "AI ProductOS", "version": 1.0}'
    data = extract_json_from_text(raw)
    assert isinstance(data, dict)
    assert data["name"] == "AI ProductOS"
    assert data["version"] == 1.0


def test_extract_markdown_json_block():
    raw = """Here is the strategic backlog generated by the AI Product Manager:
```json
{
  "epics": [
    {"title": "Autonomous Routing Engine", "priority": "High"},
    {"title": "Self-Healing JSON Parser", "priority": "Critical"}
  ]
}
```
Let me know if you need any adjustments!"""
    data = extract_json_from_text(raw)
    assert "epics" in data
    assert len(data["epics"]) == 2
    assert data["epics"][1]["title"] == "Self-Healing JSON Parser"


def test_extract_conversational_filler():
    raw = 'Certainly! {"best_case_timeline": {"duration_weeks": 6}, "risk_score": 3} That completes the simulation.'
    data = extract_json_from_text(raw)
    assert data["best_case_timeline"]["duration_weeks"] == 6
    assert data["risk_score"] == 3


def test_extract_trailing_comma_repair():
    raw = """```json
{
  "items": ["Item 1", "Item 2", ],
  "status": "active",
}
```"""
    data = extract_json_from_text(raw)
    assert data["items"] == ["Item 1", "Item 2"]
    assert data["status"] == "active"


def test_invalid_json_raises_error():
    raw = "This is just plain text without any valid JSON objects or arrays inside."
    with pytest.raises(ValueError):
        extract_json_from_text(raw)
