from pydantic import BaseModel, Field
from app.ai.agents.base import BaseAgent
from app.ai.schemas import AgentResponse


class UXAgentInput(BaseModel):
    functional_requirements: str = Field(..., description="The requirements generated by Business Analyst")


class UXAgent(BaseAgent[UXAgentInput, AgentResponse]):
    @property
    def name(self) -> str:
        return "ux_designer"

    @property
    def version(self) -> str:
        return "1.0.0"

    @property
    def description(self) -> str:
        return (
            "Responsible for defining UI user flows, listing target screens, establishing navigation guidelines, "
            "and outlining design/accessibility specifications."
        )

    def get_system_instructions(self) -> str:
        return (
            "You are the UX Designer Agent. Design interface experiences, color palettes, and component structures.\n"
            "Under the 'result' key of the AgentResponse, output:\n"
            "- user_flows: list of dicts (flow_name, steps)\n"
            "- screen_catalog: list of dicts (screen_name, description, components)\n"
            "- design_system_rec: dict of (theme_mode, primary_color, secondary_color, font_family)\n"
            "- accessibility_rules: list of strings\n"
            "- responsive_strategy: string"
        )
